INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (1,'community',NULL,'community');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (2,'housing',NULL,'housing');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (3,'jobs',NULL,'jobs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (4,'services',NULL,'services');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (5,'for sale',NULL,'for-sale');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (6,'activities',1,'activities');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (7,'artists',1,'artists');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (8,'childcare',1,'childcare');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (9,'classes',1,'classes');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (10,'events',1,'events');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (11,'general',1,'general');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (12,'groups',1,'groups');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (13,'local news',1,'local-news');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (14,'lost+found',1,'lost-found');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (15,'missed connections',1,'missed-connections');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (16,'pets',1,'pets');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (17,'politics',1,'politics');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (18,'rants & raves',1,'rants-raves');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (19,'rideshare',1,'ride-share');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (20,'volunteers',1,'volunteers');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (21,'apts / housing',2,'apts-housing');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (22,'housing swap',2,'housing-swap');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (23,'housing wanted',2,'housing-wanted');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (24,'office / commercial',2,'office-commercial');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (25,'parking / storage',2,'parking-storage');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (26,'real estate for sale',2,'real-estate-for-sale');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (27,'rooms / shared',2,'rooms-shared');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (28,'rooms wanted',2,'rooms-wanted');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (29,'sublets / temporary',2,'sublets-temporary');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (30,'vacation rentals',2,'vacation-rentals');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (31,'accounting + finance',3,'accounting-finance');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (32,'admin / office',3,'admin-office');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (33,'arch / engineering',3,'arch-engineering');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (34,'art / media / design',3,'art-media-design');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (35,'biotech / science',3,'biotech-science');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (36,'business / mgmt',3,'business-mgmt');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (37,'customer service',3,'customer-service');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (38,'education',3,'education');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (39,'food / bev / hosp',3,'food-bev-hosp');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (40,'general labor',3,'general-labor');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (41,'government',3,'government');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (42,'human resources',3,'human-resources');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (43,'internet engineers',3,'internet engineers');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (44,'legal / paralegal',3,'legal-paralegal');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (45,'manufacturing',3,'manufacturing');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (46,'marketing / pr / ad',3,'marketing-pr-ad');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (47,'medical / health',3,'medical-health');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (48,'nonprofit sector',3,'nonprofit-sector');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (49,'real estate',3,'real-estate-jobs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (50,'retail / wholesale',3,'retail-wholesale');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (51,'sales / biz dev',3,'sales-biz-dev');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (52,'salon / spa / fitness',3,'salon-spa-fitness');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (53,'security',3,'security');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (54,'skilled trade',3,'skilled trade');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (55,'software / qa / dba',3,'software-qa-dba');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (56,'systems network',3,'systems-network');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (57,'technical support',3,'technical-support');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (58,'transport',3,'transport');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (59,'tv / film / video',3,'tv-film-video');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (60,'web / info design',3,'web-info-design');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (61,'writing / editing',3,'writing-editing');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (62,'[ETC]',3,'ETC-jobs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (63,'[ part-time ]',3,'part-time-jobs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (64,'antiques',5,'antiques');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (65,'appliances',5,'appliances');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (66,'arts + crafts',5,'arts-crafts');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (67,'atv / utv / sno',5,'atv-utv-sno');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (68,'auto parts',5,'auto-parts');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (69,'aviation',5,'aviation');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (70,'baby + kid',5,'baby-kid');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (71,'barter',5,'barter');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (72,'beauty + health',5,'beauty-health');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (73,'bikes',5,'bikes');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (74,'boats',5,'boats');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (75,'books',5,'books');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (76,'business',5,'business');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (77,'cars + trucks',5,'cars-trucks');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (78,'cds / dvd / vhs',5,'cds-dvd-vhs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (79,'cell phones',5,'cell-phones');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (80,'clothes + acc',5,'clothes-acc');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (81,'computers',5,'computers');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (82,'electronics',5,'electronics');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (83,'farm + garden',5,'farm-garden');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (84,'free',5,'free');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (85,'furniture',5,'furniture');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (86,'garage sale',5,'garage-sale');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (87,'general',5,'general');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (88,'heavy equip',5,'heavy-equip');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (89,'household',5,'household');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (90,'jewelry',5,'jewelry');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (91,'materials',5,'materials');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (92,'music instr',5,'music-instr');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (93,'photo + video',5,'photo-video');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (94,'rvs + camp',5,'rvs-comp');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (95,'sporting',5,'sporting');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (96,'tickets',5,'tickets');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (97,'tools',5,'tools');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (98,'toys + games',5,'toys-games');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (99,'trailers',5,'trailers');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (100,'video gaming',5,'video-gaming');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (101,'wanted',5,'wanted');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (102,'automotive',4,'automotive');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (103,'beauty',4,'beauty');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (104,'cell / mobile',4,'cell-mobile');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (105,'computer',4,'computer');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (106,'creative',4,'creative');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (107,'cycle',4,'cycle');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (108,'event',4,'event');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (109,'farm + garden',4,'farm-garden');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (110,'financial',4,'financial');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (111,'household',4,'household');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (112,'labor / move',4,'labor-move');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (113,'legal',4,'legal-services');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (114,'lessons',4,'lessons');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (115,'marine',4,'marine');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (116,'pet',4,'pet');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (117,'real estate',4,'real-estate-services');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (118,'skilled trade',4,'skilled-trade-services');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (119,'sm biz ads',4,'sm-biz-ads');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (120,'travel / vac',4,'travel-vacation');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (121,'write / ed / tran',4,'write-ed-tran');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (122,'personals',NULL,'personals');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (123,'gigs',NULL,'gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (124,'strictly platonic',122,'strictly-platonic');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (125,'women seeking women',122,'women-seeking-women');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (126,'women seeking men',122,'women-seeking-men');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (127,'men seeking women',122,'men-seeking-women');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (128,'men seeking men',122,'men-seeking-men');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (129,'misc romance',122,'misc-romance');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (130,'casual encounters',122,'casual-encounters');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (131,'computer',123,'computer-gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (132,'creative',123,'creative-gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (133,'crew',123,'crew-gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (134,'domestic',123,'domestic-gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (135,'event',123,'event-gigs');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (136,'labor',123,'labor');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (137,'talent',123,'talent');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (138,'writing',123,'writing');
INSERT INTO `categories` (`id`,`name`,`parent_id`,`slug`) VALUES (139,'resumes',NULL,'resumes');
